- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure sudo and basic packages installed
  apt:
    name: ["sudo","curl","git","python3","python3-venv","python3-pip"]
    state: present

- name: Ensure authorized key is present for root
  authorized_key:
    user: "root"
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') | default(omit) }}"
    state: present
